# Typos configuration
# https://github.com/crate-ci/typos

[default.extend-words]
# Azure Kubernetes Service abbreviation
AKS = "AKS"
aks = "aks"
# Indian Standard Time / Istio abbreviation
IST = "IST"
# Abbreviation (e.g., 2nd -> ND)
ND = "ND"

# Add repo-specific false positives here:
# word = "word"
